<?php
// Powered X-Rere Script
// Supported I-WRAH Tools
// Punya MasbimCH
// Please don't remove tag :)

echo '#EXTINF:-1 tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/KOMPAS_TV_%282017%29.png/220px-KOMPAS_TV_%282017%29.png" group-title="LOKAL", Kompas TV
https://etslive-2-vidio-com.akamaized.net/vp9/204_stream.mpd?';
echo jembuwt('204')."\n";

function jembuwt($aw){
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'https://www.vidio.com/live/204/tokens');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

	$headers = array();
	$headers[] = 'Authority: https://www.vidio.com';
	$headers[] = 'Content-Length: 0';
	$headers[] = 'Origin: https://www.vidio.com';
	$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36';
	$headers[] = 'Dnt: 1';
	$headers[] = 'Accept: */*';
	$headers[] = 'Sec-Fetch-Site: same-origin';
	$headers[] = 'Sec-Fetch-Mode: cors';
	$headers[] = 'Referer: https://www.vidio.com/live/204-sctv';
	$headers[] = 'Accept-Encoding: gzip, deflate, br';
	$headers[] = 'Accept-Language: id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);
	if (curl_errno($ch)) {
		echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);
	$result = json_decode($result, true);
	echo $result['token'];
}
